services:
  - type: web
    name: wordpress
    env: docker
    plan: free
    dockerfilePath: ./wordpress/Dockerfile
    envVars:
      - key: WORDPRESS_DB_HOST
        value: db:3306
      - key: WORDPRESS_DB_NAME
        value: wordpress
      - key: WORDPRESS_DB_USER
        value: wordpress
      - key: WORDPRESS_DB_PASSWORD
        value: wordpress

  - type: web
    name: db
    env: docker
    plan: free
    dockerfilePath: ./db/Dockerfile
    autoDeploy: false
